### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by jjanusch** [ZeroQI/YouTube-Agent.bundle#1]
I'm trying to figure out exactly how to name the file structure so that the scanner and agent are able to pick up and download metadata for YouTube videos. I'm trying to add [this playlist](https://www.youtube.com/playlist?list=PLaAVDbMg_XAoIzvMEoPyg7mW0T0gDZezo). Judging from the docs, I should be able to do:

```
Library Root/PLaAVDbMg_XAoIzvMEoPyg7mW0T0gDZezo/Qb_Qz2bk4xQ.mp4
```

But that results in no metadata being downloaded whatsoever. I've also tried numerous other combinations such as prepending `youtube-`, prepending the exact names, using the exact names for the video, using just the exact video names, etc. I am using a TV Series library with both the agent and scanner enabled. What's the proper structure?

**Comment by jjanusch** [comment]
I think I have it working now using this format:

```
Library/Ethoslab/Project Ozone 2 [PLaAVDbMg_XAoIzvMEoPyg7mW0T0gDZezo]/Minecraft - Project Ozone 2 #1  Skyblock Reloaded (Kappa) [WNA3lsmD8M4].mp4
Library/Ethoslab/Project Ozone 2 [PLaAVDbMg_XAoIzvMEoPyg7mW0T0gDZezo]/Minecraft - Project Ozone 2 #2  Mob System [jm_lHiaSYQM].mp4
Library/Ethoslab/Project Ozone 2 [PLaAVDbMg_XAoIzvMEoPyg7mW0T0gDZezo]/Minecraft - Project Ozone 2 #3  Tinkers Smeltery [Yk8_4Y7XndY].mp4
Library/Ethoslab/Project Ozone 2 [PLaAVDbMg_XAoIzvMEoPyg7mW0T0gDZezo]/Minecraft - Project Ozone 2 #70  Bottle Neck [Qb_Qz2bk4xQ].mp4
```

**Comment by ZeroQI** [comment]
Soon it will be possible to use the channel id too...
I thought it was clear in the readme...

**Comment by 19wolf** [comment]
Does OPs naming convention work?
`Library Root//UCAL3JXZSzSm8AlZyD3nQdBA/wrTDJbaxhOI.mp4`
I have mine set up this way but it doesn't seem to be working

**Comment by ZeroQI** [comment]
Not following guidelines... This will not work
