### ISSUE TITLE
[QUESTION] Do video files require index  for YouTubeSeries agent

### ISSUE THREAD

**Issue by Gage-Irwin** [ZeroQI/YouTube-Agent.bundle#115]
When using the YouTubeSeries agent do the videos have to have the playlist index in them even for a channel? 
I have the agent "working" just want to figure out if my use case is the issue.
I have archives of completed channels no playlists no indexing.
YouTubeMovies agent works I just don't like the layout.
YouTubeSeries agent works if I include indexes in the video file names.
My current file structure is:
```
- Channel-Name-[CHANNEL_ID]
    - YYYY-MM-DD-[VIDEO_ID]-title.ext (video)
    - YYYY-MM-DD-[VIDEO_ID]-title.info.json (yt-dlp json)
    - YYYY-MM-DD-[VIDEO_ID]-title.webp (thumbnail)
```
I don't think it's a problem with the agent but I can post logs if needed.
Also I did check the regex patterns while trouble shooting and yes the CHANNEL_ID and VIDEO_ID are found by them.

**Comment by Gage-Irwin** [comment]
I rather not have playlist index in the file names because If a channel deletes a video later on it will mess up all future indexing

**Comment by ZeroQI** [comment]
Series folder to contain Playlist ID or channel ID or Playlist ID in a folder inside a folder with channel ID. Files do need video ID

**Comment by Gage-Irwin** [comment]
> 

Yes All videos have the video id in the file name and they are all located in a channel folder with the channel id in the folder name.

**Comment by Gage-Irwin** [comment]
> Series folder to contain Playlist ID or channel ID or Playlist ID in a folder inside a folder with channel ID. Files do need video ID

Yes, all video file names contain the video id and they are all located in a channel folder that contains the channel id.

**Comment by ZeroQI** [comment]
Would use the Playlist id if possible but if videos are not in the Playlist then channel id

**Comment by Gage-Irwin** [comment]
> Would use the Playlist id if possible but if videos are not in the Playlist then channel id

They do have a channel id and video id but it doesn't find the videos with YouTubeSeries unless they have an index value in the file name. I was trying to see if that is intended.

**Comment by ZeroQI** [comment]
The scanner find the videos the agent find metadata. What is an index value? Video ID?

**Comment by Gage-Irwin** [comment]
Strange in trying to reproduce my issue to better explain it I seem to have come across another issue of not all the metadata being filled in.
yt-dlp command used:
```
yt-dlp --playlist-items 1:3 --output "media/%(uploader)s-[%(uploader_id)s]/%(upload_date>%Y-%m-%d)s-[%(id)s]-%(title)s.%(ext)s" --restrict-filenames --merge-output-format mkv https://www.youtube.com/c/ShortCircuit/videos
``` 
ASS root scanner file missing?
[com.plexapp.agents.youtube.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/9730281/com.plexapp.agents.youtube.log)
![Screenshot 2022-10-06 213716](https://user-images.githubusercontent.com/91108814/194456337-512eff28-5a90-426a-b7e0-6f95a09d7558.png)
Also thanks for being really responsive and trying to help.
