### ISSUE TITLE
YoutubeSeries Agent not appearing

### ISSUE THREAD

**Issue by Not-Frosty** [ZeroQI/YouTube-Agent.bundle#117]
I've followed the instructions to unzip and place the plugin properly. It's detected by my Plex but only for the YouTubeMovie agent. I've tried reinstalling and restarting plex a few times. Any suggestions would be much appreciated, Thanks!

![image](https://user-images.githubusercontent.com/67878028/202362181-6cb413c5-0f96-4fb5-b897-dcd198c33a7d.png)

**Comment by ZeroQI** [comment]
You can only see YoutubeMovie in a Movie library...
Did you try the Plex settings to see if the youtubeSeries agent was seen ?
Did you try the same in a Series library ?
