### ISSUE TITLE
YouTube Series agent not returning all videos

### ISSUE THREAD

**Issue by clucas127** [ZeroQI/YouTube-Agent.bundle#118]
I have followed all of the instructions to setup the Agent with my Plex Library, and when I initially created a Video Library I was only given the option of using the YouTubeMovie agent. This properly found all of my videos, but I would prefer that the playlists I have downloaded be shown in a TV Series format on Plex. When I tried re-creating the Library as a TV Library, I was able to select the YouTubeSeries agent, but now only 2 of my 3 playlists are showing up, and both are missing multiple episodes.

I am new to Github and I'm not really a coder, so I apologize if I am not including all of the necessary information. I will happily share any information necessary to diagnose this issue.

**Comment by ZeroQI** [comment]
If files are not showing up or at wrong season or episode number, it is a
scanner issue, as per Absolute Series Scanner Readme first line...

Did you make sure to use ASS Scanner for you series library as per the
Readme? If so attach the ASS scanner logs for this specific library

**Comment by clucas127** [comment]
Ah okay, I didn't see the Absolute Series Scanner portion in the installation steps, but after going back through the readme I have installed it properly and changed the API Key to my own, and now everything seems to be working!

Thanks so much for the quick reply!

**Comment by ZeroQI** [comment]
Excellent.

Please refer to ASS Readme and search for: exhibit 1q
