### ISSUE TITLE
Help with reading local data

### ISSUE THREAD

**Issue by OneSteelTank** [ZeroQI/YouTube-Agent.bundle#119]
I know this program's main use is to pull metadata from YouTube itself, but I am downloading these videos in case the youtube videos get deleted, in which case the main use won't work. But you mention that it can pull metadata from .info.json files. It's not working for me, however. my goal is to get the plex page to look like [this](https://ibb.co/7Jprkr1). Plex randomly read the metadata of a video without any plug-ins or agents but since then I haven't been able to replicate it. All the pages usually just look like [this](https://ibb.co/3zxNb3r). I'm using yt-dlp and using the commands --add-metadata and --write-info-json. The json file is there, and when I used MediaInfo to look at the metadata it shows the channel name under 'artist' and the description under 'description'. But still, nothing.
The files look like this
![image](https://user-images.githubusercontent.com/30085240/206330943-474995fd-be68-4cba-a184-636454efbac0.png)
This is the command I used (I'm using Tartube): `yt-dlp --newline -i --hls-prefer-native --write-info-json --cookies E:/Tartube/cookies.txt --windows-filenames --output E:/Tartube/Unsorted Videos/%(id)s - (%(upload_date>%Y.%m.%d)s) %(title)s [%(uploader)s].%(ext)s --write-thumbnail --add-metadata https://www.youtube.com/watch?v=bABreP9sl9Q`

**Comment by ZeroQI** [comment]
This bug report miss the series name used, which should have the Playlist
or channel ID in brackets.

The video ID must be between brackets. Lm648 is not a valid YouTube video
ID.

This is a use case scenario, the Plex forum for the agent should have been
used for assistance instead.
I gave in the readme the command lines and scripts to label it properly...

Le jeu. 8 déc. 2022 à 02:06, OneSteelTank ***@***.***> a
écrit :

**Comment by OneSteelTank** [comment]
I'm not going to lie, I definitely did not look through the readme very well. Changed some stuff and now it looks like this
![image](https://user-images.githubusercontent.com/30085240/206823826-784186f3-458f-41db-9fa4-294cac7fd131.png)
pretty good. one thing that's confusing me though: in the youtubeseries settings there's an option called "media poster". i changed it from channel to episode but didnt notice any difference. i thought it would change the image in the top left to a video thumbnail. also, can you link the forum so that i can talk about the local metadata thing in the right place? i cant find it. thanks.

**Comment by OneSteelTank** [comment]
i'm going to be honest. i really didn't read through the documentation very thoroughly. made some changes and now it looks like this:
![image](https://user-images.githubusercontent.com/30085240/206824479-6b386450-ebd7-4ca4-a971-7faf91741f35.png)
pretty good! i do have one problem though, i dont know if it's a bug. in the youtubeseries settings there's an option called media poster. i changed it from channel to episode thinking it would do something like change the image in the top left to a video thumbnail but from what i can see nothing changed. any ideas? also please link me the forum so that i can get help with the local metadata thing in the right place. thanks a lot man. will be sure to donate if i remember

**Comment by ZeroQI** [comment]
one metadata is gathered, the active image won't change as the image index is set in stone. After metadata refresh, did you check if there was additional screenshots created for the episode ?
