### ISSUE TITLE
Last version crash when underscores are present

### ISSUE THREAD

**Issue by MizeryMade** [ZeroQI/YouTube-Agent.bundle#123]
It seems the change for "[Make YouTube regex compatible with TubeArchivist](https://github.com/ZeroQI/YouTube-Agent.bundle/commit/6be09f20fcede15fdf7a6c228e442433a299e938)" has broken the functionality for cases were the script was previously functioning fine. Seems maybe the RegEx needs another look?

CURRENT:

> 2023-01-16 11:59:03,984 (25f8) :  INFO (logkit:16) - populate_episode_metadata_from_api() - filename: {Clout Cancun} ~ 2022-12-13 ~  ~ When Rap & Wrestling Collide： A Deep Dive {1080p_30fps_vp9-142kbit_opus} ~ [oyWJXX1CZiE].mkv
> 2023-01-16 11:59:03,984 (25f8) :  INFO (logkit:16) - # **videoId [vp9-142kbit]** not in Playlist/channel item list so loading json_video_details
> 2023-01-16 11:59:04,025 (25f8) :  DEBUG (networking:138) - Fetching 'https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails,statistics&id=vp9-142kbit&key={KEY}' from the HTTP cache
>  2023-01-16 11:59:04,072 (25f8) :  INFO (logkit:16) - Error: "list index out of range"
>  2023-01-16 11:59:04,072 (25f8) :  INFO (logkit:16) - [ ] genres:   "[]"
>  2023-01-16 11:59:04,072 (25f8) :  INFO (logkit:16) - === End Of Agent Call, errors after that are Plex related ===

REVERTED:

> 2023-01-16 11:59:54,108 (41ac) :  INFO (logkit:16) - populate_episode_metadata_from_api() - filename: {Clout Cancun} ~ 2022-12-13 ~  ~ When Rap & Wrestling Collide： A Deep Dive {1080p_30fps_vp9-142kbit_opus} ~ [oyWJXX1CZiE].mkv
> 2023-01-16 11:59:54,108 (41ac) :  INFO (logkit:16) - # **videoId [oyWJXX1CZiE]** not in Playlist/channel item list so loading json_video_details
> 2023-01-16 11:59:54,151 (41ac) :  DEBUG (networking:138) - Fetching 'https://www.googleapis.com/youtube/v3/videos?part=snippet,contentDetails,statistics&id=oyWJXX1CZiE&key={KEY}' from the HTTP cache
> [...]
> 2023-01-16 11:59:54,938 (41ac) :  INFO (logkit:16) - === End Of Agent Call, errors after that are Plex related ===

**Comment by ZeroQI** [comment]
```
Old YOUTUBE_VIDEO_REGEX = Regex('\[(?:youtube\-)?(?P<id>[a-z0-9\-_]{11})\]', Regex.IGNORECASE)
New YOUTUBE_VIDEO_REGEX = Regex('[\[_](?:youtube\-)?(?P<id>[a-z0-9\-_]{11})[\]_]', Regex.IGNORECASE)
```

New regex output gives videoId [vp9-142kbit] which is wrong, should be videoId [oyWJXX1CZiE] 
File: `A Deep Dive {1080p_30fps_vp9-142kbit_opus} ~ [oyWJXX1CZiE].mkv`
It's the underscore that mess it up, but they are supposed to be at the beginning and the end...

https://github.com/ZeroQI/YouTube-Agent.bundle/blob/6be09f20fcede15fdf7a6c228e442433a299e938/Contents/Code/__init__.py#L574
Replace line 574 with the below and report please as i do not use this agent (despite being the main coder) and correct blind:
`YOUTUBE_VIDEO_REGEX = Regex('^[\[_](?:youtube\-)?(?P<id>[a-z0-9\-_]{11})[\]_]$', Regex.IGNORECASE)`

**Comment by ZeroQI** [comment]
I am really bad at regex, and don't use the agent myself so tricky to reproduce...

https://regex101.com/r/BFKkGc/3/ 
- [\[_](?:youtube\-)?(?P<id>[a-z0-9\-_]{11})[\]_]
- 20221213_oyWJXX1CZiE_.mp4
- A Deep Dive {1080p_30fps_vp9-142kbit_opus} ~ [oyWJXX1CZiE].mkv

`_vp9-142kbit_ is exactly 11 characters long between underscores, that is why it fails... `

This may work: (set beginning and end, and a variable unnamed group to steal the rest in front)
YOUTUBE_VIDEO_REGEX = Regex('^(\w+?)[\[_](?:youtube\-)?(?P<id>[a-z0-9\-_]{11})[\]_]$', Regex.IGNORECASE)
