### ISSUE TITLE
One channel not matching

### ISSUE THREAD

**Issue by mylogon341** [ZeroQI/YouTube-Agent.bundle#133]
I have about 12 channels so far set up. All but one are matching and fetching metadata + thumbnails properly. The channel in question is `Cathode Ray Dude[UCXnNibvR_YIdyPs8PZIBoEw]`. When I have tried to "Fix match" it just changes the channel name to the path of the directory, less the channel ID, ie
<img width="600" alt="Screenshot 2023-05-27 at 12 15 27 am" src="https://github.com/ZeroQI/YouTube-Agent.bundle/assets/5493303/943b67ff-680a-4ff7-8955-6bcab530ad60">
To be clear - the path to that channel is 
`/youtubes/Cathode Ray Dude[UCXnNibvR_YIdyPs8PZIBoEw]` in the Plex container.

The naming format for all channels and videos are exactly the same as I have started using [tubesync](https://github.com/meeb/tubesync) to grab them for me. All other channels are presenting as expected, for example 

<img width="600" alt="Screenshot 2023-05-27 at 12 17 45 am" src="https://github.com/ZeroQI/YouTube-Agent.bundle/assets/5493303/c92b11a4-b8c2-42ca-932a-207f3197ebdd">

I have no idea why it's doing this - my chaos theory is that the title of the channel is confusing the agent. It's presentable title is `Cathode Ray Dude [CRD]` (seen [here](https://www.youtube.com/channel/UCXnNibvR_YIdyPs8PZIBoEw)) and those square brackets are throwing the whole thing off kilter.

Any suggestions to help me make my collection smoother, that'd be great :)
Thanks

**Comment by mylogon341** [comment]
I have no idea what is going on here.. I looked further into the logs and there was an API token error. I generated a new token and now the channel loads properly. It'd make a lot more sense if they all failed, but it was just this one. Unless the others had cached and appeared to be working now. I'm too tired to be going through the logs fully to unpick what happened or if they're safe to just dump here without exposing anything. If I'm good to drop them in here, I can do if anyone is interested to take a look. Either way it _seems_ to be working for now again 🤨

**Comment by ZeroQI** [comment]
Space before square bracket missing

**Comment by mylogon341** [comment]
Well I did try that before fixing the API key and it made no difference so I reverted it. Once I fixed the key, it now works as expected without the space, so I assume the space isn't that important..? I'm guessing you'd know better, but it is curious how it's all working now with 12 channels, none of which have a leading space for the channel id.

**Comment by ZeroQI** [comment]
After review space doesn't matter. https://github.com/ZeroQI/YouTube-Agent.bundle/blob/master/Contents/Code/__init__.py#L568
Square brackets could throw the channel detection off indeed
