### ISSUE TITLE
Agent works for Library type "Movies" and "TV Shows" but does not appear for "Other Videos"

### ISSUE THREAD

**Issue by razordynamics** [ZeroQI/YouTube-Agent.bundle#137]
Hello, I'd like to be able to use the YouTube Agent to scan metadata from YT movies but I want to be able to display the videos/thumbs/posters as landscape. I can do this if I make my Library type "Other Movies" but then I lose the ability to scan/read metadata with this plugin. 

Are there plans to adapt this plugin for use in Other Videos/Personal Videos, so that landscape posters can be used?

**Comment by ZeroQI** [comment]
How is that any different from this prior bug report: https://github.com/ZeroQI/YouTube-Agent.bundle/issues/11

To my knowledge, there is no agent for Other Videos/Personal Videos...

So in short, not possible by me and I believe not possible at all. I did look at formating thumbnails and failed loading python image library when I tried

**Comment by razordynamics** [comment]
Yes, I saw #11. There's been no updates or movement in two years on that issue, so I opened a new one to see what sort of progress (if any) has been made. Of note, one commenter noted that they had some sort of hacky workaround that worked for them.

**Comment by ZeroQI** [comment]
I did try to include the fix mentioned in the last message on this thread but nobody tested it, so...
