### ISSUE TITLE
Director vs Cast fields

### ISSUE THREAD

**Issue by razordynamics** [ZeroQI/YouTube-Agent.bundle#139]
Hello, this is more of a question than an issue - why is it that some videos get scanned and have "Cast" in their metadata, and some only have "Director?" How can I configure the scanner to fill both Cast and Director fields consistently?

I'm using --write-info-json and --no-clean-json on yt-dlp. Is this issue a function of yt-dlp flags or scanner settings? My YT library is set up as Movies, not TV shows (by preference).

**Comment by ZeroQI** [comment]
Scanner do not fill cast or director metadata,  the agent does that in two ways, playlist or channel, so i guess channel used for movie library...

https://github.com/ZeroQI/YouTube-Agent.bundle/blob/master/Contents/Code/__init__.py#L409

Yt-dlp? Not supported, unsure if it creates the same files as youtube-dl

Support thread for agent:

https://github.com/ZeroQI/YouTube-Agent.bundle/issues (proven or confident enough it's a bug. Include the symptoms, the logs mentionned above)
https://forums.plex.tv/discussion/83106/rel-youtube-metadata-agent/p5 (not sure if bug, if bug will create a gihub issue ticket)

Forum should gave been used according readme, closing. Fyi i do not use this agent personally so do not reproduce issues, i do answer if logs attached but do not revisit open tickets as you can see, and youtube agent is my less beloved project... I will transfer project ownership to whoever want to continue the support and development...
