### ISSUE TITLE
No matter what I do metadata agent only populates date as episode title.

### ISSUE THREAD

**Issue by tc36** [ZeroQI/YouTube-Agent.bundle#142]
I'm trying to get Tubesync setup with plex. Youtube metadata agent refuses to play nicely.

**In tubesync:**

Directory is set to "Channel Name [Channel ID]"
filename for videos: {title_full} - {yyyy_mm_dd} - {format} [{key}].{ext}

**In Plex:**

Using Absolute Scanner and YT metadata agent
I have my folders setup as such:
"channel [channelid]/show title [showid]"
Channel info populates fine. Show info only populates the date as the title.

**Comment by ZeroQI** [comment]
Is showid the Playlist Id? If not, the folder is surplus to requirement
Cannot see videoid in filename, which is a requirement

**Comment by ZeroQI** [comment]
Is showid the Playlist Id? If not, the folder is surplus to requirement
Cannot see videoid in filename, which is a requirement
