### ISSUE TITLE
Am I missing something basic? Confused by ReadMe

### ISSUE THREAD

**Issue by bwt615** [ZeroQI/YouTube-Agent.bundle#145]
Absolute Series Scanner
YouTube-Agent

Folder Structure Example (downloaded using tubesync):

/video/Philip DeFranco [UClFSU9_bUb4Rc6OYfTt5SPw]/20231011 [MeVWAurJ2ps].mkv

What I get (random duplicates, some tiitles not functioning):

![image](https://github.com/ZeroQI/YouTube-Agent.bundle/assets/48396397/2f7a38ee-6e53-432a-ad53-6f38a14a6902)

Am I missing something glaring? The readme examples for TV series all have three levels of hierarchy, which confused me.

**Comment by bwt615** [comment]
To be clear - downloading this with tube sync

**Comment by ZeroQI** [comment]
Bug with videos released the same day, in youtube channel mode, due to scanner lilitations
Use playlist id if possible, or change the day one day before or after to avoid duplicate dates

**Comment by bwt615** [comment]
> Bug with videos released the same day, in youtube channel mode, due to scanner lilitations
> 
> Use playlist id if possible, or change the day one day before or after to avoid duplicate dates 

Thank you for the response!! None of these are the same day though. Could it be a timezone issue or something?

**Comment by ZeroQI** [comment]
10/19/2023 twice but could be the metadata...
You didn't include the scanner logs so...

Scanner use file last modification date and i gave the commands to tell filetube to match it on youtube release date, maybe you didn't do that...

**Comment by bwt615** [comment]
Logs would help eh?
[com.plexapp.agents.youtube.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/13909439/com.plexapp.agents.youtube.log)
[Logs.zip](https://github.com/ZeroQI/YouTube-Agent.bundle/files/13909442/Logs.zip)

**Comment by ZeroQI** [comment]
Would you have the scanner log output for this series please? It should be in a subfolder with the library name, as i suspect a possible scanner issue...

**Comment by bwt615** [comment]
I'm seeing no series subfolder! Withing Plex Logs I have one folder -> PMS Plugin Logs and within that those youtube log files were the only thing that resembled the scanner.

**Comment by bwt615** [comment]
> Would you have the scanner log output for this series please? It should be in a subfolder with the library name, as i suspect a possible scanner issue... 

Anywhere else worth looking?

**Comment by ZeroQI** [comment]
Could be in hama agent data folder depending its version if you have HAMA agent installed

Is this a youtube playlist as well by any chance?

**Comment by bwt615** [comment]
Not that I'm aware of! It's done by the channel.

A few updates - at least the scanner is logging. This isn't totally explicit from the readme but we're best to use the ASS agent, right?

[ASS.zip](https://github.com/ZeroQI/YouTube-Agent.bundle/files/13952575/ASS.zip)

Could the agent be not running at all? Any known issues with M1 Macs?

**Comment by bwt615** [comment]
Ok - have some logs now. I think it didn't like one videos path with a hyphen in it, since removed that. Any other things you see that are concerning?
[com.plexapp.agents.youtube.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/13956585/com.plexapp.agents.youtube.log)

**Comment by bwt615** [comment]
Ok this is immediately working better with a setting change, per this comment:

https://github.com/meeb/tubesync/issues/455#issuecomment-1919070474

I think the additional files is helping. Any idea where he got the youtube2?

**Comment by ZeroQI** [comment]
Its use case is describbed in absolute series scanner readme...

**Comment by bwt615** [comment]
> Its use case is describbed in absolute series scanner readme...

I saw it for movie library - but this was for a Tv one! In your TV library example you don't mention appending [YouTube-UCXXXX] (let alone youtube2). Either that or the local metadata files is already far cleaner.

**Comment by ZeroQI** [comment]
Added example to ASS readme
you can just use the playlist or channel id or use youtube- before it, works the same, but using youtube2-xxxx allow to have the year as season

**Comment by bwt615** [comment]
> Added example to ASS readme you can just use the playlist or channel id or use youtube- before it, works the same, but using youtube2-xxxx allow to have the year as season

Thanks, awesome! Hopefully this saves someone in the future. It is working fantastically so far - will report back on whether it fixes all my problems but essentially needed to rebuild my tubesync library.

**Comment by wjlester** [comment]
> > Added example to ASS readme you can just use the playlist or channel id or use youtube- before it, works the same, but using youtube2-xxxx allow to have the year as season
> 
> Thanks, awesome! Hopefully this saves someone in the future. It is working fantastically so far - will report back on whether it fixes all my problems but essentially needed to rebuild my tubesync library.

It helped me! Thanks for posting the “youtube2”. My channels are finally correct!

**Comment by bwt615** [comment]
As an update - all my channels are working BEAUTIFULLY - thank you!! Great plugin now that it is working with my setup.
