### ISSUE TITLE
Breaks on playlists where new episodes become #1 and others are pushed back

### ISSUE THREAD

**Issue by beren12** [ZeroQI/YouTube-Agent.bundle#147]
Have the Stephen Colbert monologues but new episodes don't show up. The playlist has the newest episode as ep1, the 2nd newest is ep2, etc. Plex seems to not show new episodes even after scanning, and there doesn't seem to be any way to override/fix the order. https://www.youtube.com/playlist?list=PLiZxWe0ejyv8CSMylrxb6Nx4Ii2RHbu_j

**Comment by ZeroQI** [comment]
It detects pkaylist in reverse order by using file creation date on disk.
You musn't have used given youtube-dl code tgat replace file cezation date on disk with youtube publication date. Tried youtube2 mode?

**Comment by beren12** [comment]
I've been using the movie section as a work around, but would rather go back to it being a show. The movie files do have the upload date as the modification date.

```-rw-r--r-- 1 chris chris  9.7K Dec  3  2023 2016-06-23 - Hillary_Clinton_Questions_Donald_Trump_s_Business_Record [yx2JSkUWhqU].en.srt
-rw-r--r-- 1 chris chris  669K Dec  3  2023 2016-06-23 - Hillary_Clinton_Questions_Donald_Trump_s_Business_Record [yx2JSkUWhqU].info.json
-rw-r--r-- 1 chris chris   29M Jun 23  2016 2016-06-23 - Hillary_Clinton_Questions_Donald_Trump_s_Business_Record [yx2JSkUWhqU].mp4
-rw-r--r-- 1 chris chris  3.3K Dec  3  2023 2016-06-24 - Donald_Trump_Has_Left_The_Country [sZO9hPTqhuI].en.srt
-rw-r--r-- 1 chris chris  669K Dec  3  2023 2016-06-24 - Donald_Trump_Has_Left_The_Country [sZO9hPTqhuI].info.json
-rw-r--r-- 1 chris chris  9.9M Jun 24  2016 2016-06-24 - Donald_Trump_Has_Left_The_Country [sZO9hPTqhuI].mp4```

**Comment by ZeroQI** [comment]
Agent logs missing
Scanner logs missing
Foldername missing
Insufficiant data, and fyi i do NOT reproduce issues, even more so for youtube agent which i regret coding to this day.
