### ISSUE TITLE
Library access denied

### ISSUE THREAD

**Issue by marshallverbsky** [ZeroQI/YouTube-Agent.bundle#150]
More than happy to pay the RTFM tax if this has been explained elsewhere, just not sure of my next steps.
Channel metadata populates fine, video metadata does not.
Getting a Library Access Denied error in agent log and Cannot Read Model error in system log.

[com.plexapp.agents.youtube.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/15172686/com.plexapp.agents.youtube.log)
[com.plexapp.system.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/15172687/com.plexapp.system.log)

**Comment by ZeroQI** [comment]
At a quick glance:
- not using absolute series scanner so it skips square brackets in filenames
- plex id file missing so no access to plex library file to determine root folder
