### ISSUE TITLE
Plex deprecating plug-ins (scanners and agents)

### ISSUE THREAD

**Issue by micahmo** [ZeroQI/YouTube-Agent.bundle#152]
Hey @ZeroQI! I haven't been around in a long time because both ASS and YTA have been working flawless for me for years! I've thanked you before, but I'll thank you again. Your work is benefiting me every single day. 😊

I recently read an article from the Plex team saying that it's on their roadmap to deprecate Python-based plug-ins, including scanners and agents.

https://forums.plex.tv/t/important-information-for-users-running-plex-media-server-on-nvidia-shield-devices/883484

> Way back in 2018 [we announced the retirement of some features 47](https://forums.plex.tv/t/discontinuation-of-plugins-watch-later-recommended-and-cloud-sync/312312) which included support for plug-ins for integrating third-party audio/video channels. We also noted that this wouldn’t affect scanners and agents which rely on some of the same plug-ins infrastructure, but as this framework is built on-top of a now unsupported version of Python, we are announcing today that we’ll be removing support for plug-ins entirely going forward.

> . . .

> We are working on a solution to continue supporting third-party metadata agents but have nothing further to share at this time. We will be in touch with the development community when we’re ready to share what comes next, but rest assured that we are committed to not remove Python-based plugins from the main operating systems supported by PMS without first providing a viable alternative to developers and users.

> While there are currently no plans to support third-party scanners once the plug-ins are removed, we will be open to making our built-in scanners more extensible if the need arises.

Obviously this is a bit concerning! They claim that there will be a way to "continue supporting third-party metadata agents", but they may very well require extensive changes. And more concerning, they have "no plans to support third-party scanners", which would definitely break YTA as it relies on ASS.

Obviously there is nothing to do right now as they have not made any concrete plans or changes, but I just wanted to make you and the community aware that this is coming!

**Comment by ZeroQI** [comment]
YTA relies on scanner for playlist but not so much, but the date based numbering is not perfect and broken for multiple release on same date, some code was added to correct that but now not zorking seemingly...
There is no API yet, but it will be REST based and require a rewrite but could be done in many languages but need a rewrite and it to run as a program seemingly. We have to wait for the change and new metadata agent documentation in the meantime
