### ISSUE TITLE
Release dates are now coming up incorrectly

### ISSUE THREAD

**Issue by Tripletap007** [ZeroQI/YouTube-Agent.bundle#153]
Apparently something happened a while back to where only the year metadata seems to save ok, but everything across multiple libraries this year has been incorrectly storing as 1-1-2024 and I have a few hundred items that are set to this date now.  I have updated/replaced to the latest agent bundle but it's the same issue

**Comment by ZeroQI** [comment]
What last modification date are the files on disk? Same one?

**Comment by Tripletap007** [comment]
No. Shortly after I noticed this happening, I updated to the latest copy on here but the problem persists.

**Comment by ZeroQI** [comment]
Logs missing to troubleshoot

**Comment by Xsphyre** [comment]
Can confirm this on my end too, been having this recently out of nowhere too. New items are now showing the filepath as the channel name as well and overall the entire matching seems to be completely broken. Maybe YouTube changed something?

**Comment by ZeroQI** [comment]
Most likely... 
Logs missing to troubleshoot

**Comment by Xsphyre** [comment]
Which log(s) do you need and where are they located, and how to generate the issue in the log, do a scan, refresh metadata or?

**Comment by ZeroQI** [comment]
From readme troubleshooting section:

including all the following logs: (location: https://support.plex.tv/hc/en-us/articles/200250417-Plex-Media-Server-Log-Files)
[...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.Youtube-Agent.log (Agent logs)

I do not use the agent myself nor Plex anymore, so will NOT reproduce issues and rely on logs to identify issues

**Comment by Tripletap007** [comment]
I apologize, little bit of life happened the last few weeks but here are mine.  Each of the incorrect dated videos now has the date of "2024-01-01" and it looks like a refresh of other files gets overwritten with that as well. 
 
[com.plexapp.agents.youtube.log](https://github.com/user-attachments/files/17892099/com.plexapp.agents.youtube.log)
[com.plexapp.agents.youtube1.log](https://github.com/user-attachments/files/17892100/com.plexapp.agents.youtube1.log)
[com.plexapp.agents.youtube2.log](https://github.com/user-attachments/files/17892101/com.plexapp.agents.youtube2.log)
[com.plexapp.agents.youtube3.log](https://github.com/user-attachments/files/17892102/com.plexapp.agents.youtube3.log)
[com.plexapp.agents.youtube4.log](https://github.com/user-attachments/files/17892103/com.plexapp.agents.youtube4.log)
[com.plexapp.agents.youtube5.log](https://github.com/user-attachments/files/17892104/com.plexapp.agents.youtube5.log)

And dude, you probably don't hears this enough but you are amazing for making this agent.  My life is seriously like 20% better because of it.  But I will say a little piece inside me died when you wrote you don't use it or Plex any more...moved to Jellyfin or what?

**Comment by ZeroQI** [comment]
I use a Synology NAS with Plex installed, but hardly used Plex and now don't at all...
Haven't downloaded in a while so all I have is few years old so interest lowers over time....
Lost the drive, getting old (57)...

[com.plexapp.agents.youtube1.log](https://github.com/user-attachments/files/17892100/com.plexapp.agents.youtube1.log)
2024-11-23 15:26:30,059 (567c) :  INFO (logkit:16) - Place correct Plex token in C:\Users\tripl_000\AppData\Local\Plex Media Server\X-Plex-Token.id file or in PLEX_LIBRARY_URL variable in Code/__init__.py to have a log per library - https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token, Error: HTTP Error 401: Unauthorized
X:\Downloads HDD\Youtube\Music Videos\Lazy Lover [ETe7BPzu5Ys]
2024-11-23 15:26:33,447 (6d10) :  INFO (logkit:16) - date:  "**2008-06-19** 20:10:12+00:00"

Please Place correct Plex token in C:\Users\tripl_000\AppData\Local\Plex Media Server\X-Plex-Token.id file or in PLEX_LIBRARY_URL variable in Code/__init__.py to have a log per library, but unlikely to resolve this issue, but that would be best practice to avoid bugs

Movie code is 300-334 with 306 displaying the date and 307 setting it https://github.com/ZeroQI/YouTube-Agent.bundle/blob/master/Contents/Code/__init__.py#L306
```
      date                             = Datetime.ParseDate(json_video_details['snippet']['publishedAt']);  Log('date:  "{}"'.format(date))
      metadata.originally_available_at = date.date()
```

movie year seem ok, please confirm it is the field "originally_available_at", but date is OK in the json file and in the log output, so it does seem like a plex side bug...

**Comment by Tripletap007** [comment]
So when I check the "originally_available_at" value in then "view XML" tab on individual items, it does still list the date as '2024-01-01'.  I obviously don't know how any of this works but I'm assuming the youtube agent is pulling it correctly, is the problem transferring it over to Plex's metadata?

**Comment by ZeroQI** [comment]
The agent give a date to the video "originally_available_at" metadata field and Plex XML do not reflect that...
You most likely have a corrupted Plex database or a Plex issue, it would be a different story if it showed "2024-11-23 15:26:33,447 (6d10) : INFO (logkit:16) - date: "2024-01-01 ..."" but that is nt the case

**Comment by Tripletap007** [comment]
Probably a Plex issue then.  I just ran the Sqlite database integrity checker (which came back with nothing) and I ran the "vacuum" command as well but still getting the same borked dates.  Ah well...I had everything sorted by release date but sorting by date added is the next best thing.  I appreciate your time.
