### ISSUE TITLE
Season Grouping Bug when Channel ID in youtube.id file

### ISSUE THREAD

**Issue by Selkie707** [ZeroQI/YouTube-Agent.bundle#16]
Cody'sLab\Cheap Camera, Light bulb, Survive [cjFSyBsRkCw].mkv
channel ID in youtube.id
_All episodes put in specials_

Internet Comment Etiquette with Erik [UCyWDmyZRjrGHeKF-ofFsT5Q]\Internet Comment Etiquette - 'Things You're Doing Wrong' [0m_cuVJu1Ig].mkv
_Episodes put into season by year_

I discovered this because of another (feature request? bug?) in that channels that have nicknames instead of the string of characters id are not identified with the agent. Youtube-dl's uploader_id filename variable always grabs the nickname if it exists so autograbbed channels don't work properly yet.

Thanks a bunch for working on this agent, proper youtube support for plex is almost there. With the above bug fixed it would now be possible to mass download entire channels with a simple Channelname [ID]/ VIDEONAME [ID] fileformat.

Edit: A good channel for testing this that does get its nickname grabbed by youtube-dl is CodysLab
[https://www.youtube.com/channel/UCu6mSoMNzHQiBIOCkHUa2Aw](https://www.youtube.com/channel/UCu6mSoMNzHQiBIOCkHUa2Aw)

**Comment by ZeroQI** [comment]
Season number is decided by the scanner
Are you using Absolute Series Scanner with the agent?

**Comment by ZeroQI** [comment]
Some if file simplification was published recently...
Could you please attach the scanner logs located in:
PLEX_ROOT/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs (even if Hama isn't installed)
I will change the location to the Plex logs folder at some point but have no time at the moment
Will reproduce with the same filenames to test and solve the issue

**Comment by Selkie707** [comment]
sure:
[Logs.zip](https://github.com/ZeroQI/YouTube-Agent.bundle/files/2367066/Logs.zip)

**Comment by ZeroQI** [comment]
@Selkie707 That helps, thanks. Notes
- Please remove the square brackets around the channel ID in the youtube.id file
- force channel id (UC...) or playsiilt ID (PL...) on series folder or the series field will not be populated, it is because channel names are not unique, so using the channel ID is a sure thing...

**Comment by Selkie707** [comment]
Thanks man, removing the brackets totally fixed it.
With how much development youtube-dl has I'm suprised there isn't an option to force the channel id to the UC format by now.

**Comment by ZeroQI** [comment]
Playlist URL works with youtube-dl...
Not sure about channel URL, but worth a try
