### ISSUE TITLE
TV Show doesn't get a proper name.

### ISSUE THREAD

**Issue by tmfksoft** [ZeroQI/YouTube-Agent.bundle#19]
When the agent scans it correctly labels individual episodes but fails to label the show.
The show simply picks up the file path for the channel.

For example, I have a King of Random folder with some videos in, the show ends up being named "E:\Plex\YouTube\UC1zZE_kJ8rQHgLTVfobLi_g" rather than using the channels name.

Is this intentional or overlooked?

Thanks for working on a great plug-in 👍

**Comment by ZeroQI** [comment]
Not intended. I would need the scanner and agent log to narrow down however

**Comment by ZeroQI** [comment]
Thanks for that

I never had a youtube id with an underscore, and really bad with regex, so good to know
need to check if the following code works
```
displayname = media.title if movie else media.show
filename = os.path.splitext(os.path.basename(media.items[0].parts[0].file if movie else media.filename))[0]
```
