### ISSUE TITLE
Auto-populate collection

### ISSUE THREAD

**Issue by kade-robertson** [ZeroQI/YouTube-Agent.bundle#2]
I tend to organize stuff into collections since it displays better. Can an option be added (similar to the Director populating option) to set this as well? I would just set it to the creator's name. If there is relevant documentation to set this up I can probably do this myself, but I can't seem to find anything helpful.

**Comment by ZeroQI** [comment]
@kade-robertson way ahead of you :D...
If you use one grouping folder and it has more than one playlist/channel(support in progress) then a collection tag with the folder is automatically added (lines 175-211 about)

i am actively fully re-writing the youtube agent to support channels as we speak and simpler code. 
I have a faint hope to have donations (link in the read-me) if it performs well.

**Comment by ZeroQI** [comment]
Updated the code to simplify it extremely, allow channels and also match per video id as fallback
If putting multiple YouTube Videos in a folder The agent will detect grouping folders and create a collection. Let me know if it doesn't. closing in the meantime
