### ISSUE TITLE
youtube.id file syntax?

### ISSUE THREAD

**Issue by FoxBJK** [ZeroQI/YouTube-Agent.bundle#22]
It's not clear what the proper syntax is for a youtube.id file. I have dozens of playlists already downloaded and organized in a way that won't work for this agent. Trying to figure out if I can avoid renaming everything, but I can't find any example of what the youtube.id file is supposed to look like.

**Comment by ZeroQI** [comment]
Are you using my scanner?
'youtube.id' file containing the youtube id (playlist or channel)

**Comment by FoxBJK** [comment]
Yes but it won't work until I rename my files. I'm wondering if I can just have a YouTube.id file in the folder that has all the videos' info

**Comment by ZeroQI** [comment]
In series folder yes, not in season folder.

**Comment by FoxBJK** [comment]
What's the syntax for the file? Is it a JSON? CSV?

**Comment by ZeroQI** [comment]
Just the id in the file no line feed
