### ISSUE TITLE
The Agent loads 2 Posters, one is correct and one is wrong. It always uses the wrong one

### ISSUE THREAD

**Issue by dunklesToast** [ZeroQI/YouTube-Agent.bundle#26]
So I just loaded some videos of a german youtuber and somehow the Agent loads two thumbnails.
The first thumbnail is always wrong and the seconds one is the correct one. I don't know why this happens. The File Structure is as follows:

```
WALULIS [UChkVOG0PqkXIHHmkBGG15Ig]
    ├── WALULIS - Der Bachelor - Weichgespült _ WALULYSE [8cBeieDxAAg].mkv
```

or with params:
```
CHANNEL_NAME [CHANNEL_ID]
    ├── CHANNEL_NAME - VIDEO_NAME [VIDEO_ID].mkv
```

Any idea how to fix this?

![image](https://user-images.githubusercontent.com/17279485/51805897-71f55e00-2273-11e9-9b70-8019c6c176aa.png)

By the way: It does this for all videos (~300)

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/YouTube-Agent.bundle/blob/master/Contents/DefaultPrefs.json
did you select channel or episode as media poster source?

**Comment by dunklesToast** [comment]
I tried both, channel and episode.

With "plex dance" you mean delete the library and add it again?

**Comment by ZeroQI** [comment]
http://lmgtfy.com/?iie=1&q=plex%20dance

**Comment by ZeroQI** [comment]
Any change after the Plex Dance?

**Comment by dunklesToast** [comment]
I am currently maintaining the Hardware my PleX is running on. I’ll answer you Thursday / Friday. Sorry

**Comment by ZeroQI** [comment]
Any update?

**Comment by dunklesToast** [comment]
Well. I reinstalled Plex due to the hardware swap and now it works fine!
