### ISSUE TITLE
Can't make Plugin work

### ISSUE THREAD

**Issue by advokatb** [ZeroQI/YouTube-Agent.bundle#31]
Hi. I have such folder structure
```
e:\video\WoT\Evil Granny\Т-62А - ТАЩИТ КАК В СТАРЫЕ ДОБРЫЕ - МЕДАЛЬ ПУЛА-DZIndb-5Y3c.mp4
e:\video\WoT\Amway921\AMX 40 - Этот танк просто дичь - Мировой рекорд WN8 за одну катку-8pgtOtUhoyM.mp4
e:\video\WoT\Sklad Lebwi\КОРМ2. ФЛАБЕР УЧИТЕЛЬ _ ЭПИЧНЫЕ БОИ ПРОТИВ P_BY (GROMZOR) (Ч2) _ WORLD OF TANKS-wAjjB_KLhgg.mp4
```

So I have YouTube ID in filename but folders containing this videos are named by me not by official name of YouTube  channel where I get this videos.
This configuration won't work with your plugin?

For now I get this (path to parent folder instead of any metadata)

![изображение](https://user-images.githubusercontent.com/6189889/66718580-11e91c80-edee-11e9-9735-b96fc9fde87f.png)

while filename is 

```
e:\video\WoT\Amway921\Primo Victoria - Это вам не OFFSPRING-s3ea945_jfc.mp4
```

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/YouTube-Agent.bundle/blob/master/README.md

> Requirements
> 
> Please use the Absolute Series Scanner to scan your media and leave the YouTube id in the series/movie title
> leave the YouTube video ID on every file
> **Playlist (preffered) id** OR **Channel id** on series foldername (as Search() need to assign an id to the series)

Since requirements are present in the readme and not followed, closing.

**Comment by advokatb** [comment]
1. Here is the channel videos are related to https://www.youtube.com/channel/UCLZIN4aTXYm92c1ENyN8KmA
2. I'm done with Absolute Series Scanner.py in d:\User\Plex Media Server\Scanners\Series\
3. Here are both channel ID in folder name and video ID in filename http://prntscr.com/pisv6d
4. That is what I get in result http://prntscr.com/pisvgu

Where is my fault? Please point

**Comment by ZeroQI** [comment]
Requirements:
- Pleave the YouTube video ID on every file: [8pgtOtUhoyM]
- Playlist id (preffered) OR Channel id on series foldername: [UCLZIN4aTXYm92c1ENyN8KmA]
Please follow this naming convention:
- e:\video\WoT\Amway921 [UCLZIN4aTXYm92c1ENyN8KmA]\AMX 40 - Этот танк просто дичь - Мировой рекорд WN8 за одну катку [8pgtOtUhoyM].mp4
