### ISSUE TITLE
Metadata stopped working; updated ASS and YA and rebooted server

### ISSUE THREAD

**Issue by jcandresen** [ZeroQI/YouTube-Agent.bundle#32]
![image](https://user-images.githubusercontent.com/23084292/67629581-525c8780-f83d-11e9-8d03-230b77d3c08c.png)

i guess its still able to find the description or maybe that's from the previous data. 

i'm not very good at this there plex thing here so let me know what to provide and i'll provide it.

**Comment by ZeroQI** [comment]
Seem like a movie library so Ass woul play no role there...
Scanner logs and agent logs needed.

**Comment by jcandresen** [comment]
> Seem like a movie library so Ass woul play no role there...
> Scanner logs and agent logs needed.

Wicked bud, where do I grab those from?

**Comment by ZeroQI** [comment]
Plex Media Server\Logs\PMS Plugin Logs\com.plexapp.agents.youtube.log
Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\library\series title.scanner.log

**Comment by ZeroQI** [comment]
Did you find them?

**Comment by ZeroQI** [comment]
Did you find them?

**Comment by ZeroQI** [comment]
Closing as no logs provided despite troubleshooting steps in readme with logs location
- [...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.Youtube-Agent.log (Agent logs)
- [...]/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.system.log (show why the agent cannot launch)
