### ISSUE TITLE
Can't get the right order for series

### ISSUE THREAD

**Issue by vic1707** [ZeroQI/YouTube-Agent.bundle#34]
![error sorting ep](https://user-images.githubusercontent.com/28602203/68416661-38a03600-0195-11ea-9e4f-c3ac68a66c3d.png)

I need some help to get my series sorted correctly, now there downloaded via youtube-dl with the command : 

`youtube-dl.exe -v -i -o "./%(uploader)s/%(uploader)s - %(playlist_title)s [%(channel_id)s]/%(title)s [%(id)s].%(ext)s" -f bestvideo+bestaudio -a url.txt`

But as you can see i can't get them properly sorted (even when adding [00X] with the correct numerotation before the title of the file).

Is there a way to get the series correctly sorted?

**Comment by ZeroQI** [comment]
I regret ever making this agent as I got one 15 and one 5 euro donation for it total to date...
- This is not a bug
- It could have made a good post on plex forums to let other people respond and bump the thread at the same time...
- a channel episode doesn't have set numbers, they are numbered per age...
- a playlist episode has an episode number

Please use the Playlist ID for the folder: "Bazaar du grenier - (Let's Play narratif) Stranded Deep [PLWmL9Ldoef0tTuCzNulELa1U_Dj_Dyj2r]"...

`you didn't read the requirements on the readme the first time, so please re-read the part: "If you ask for something already answered in the readme, or post scanner issues on the agent page or vice-versa, please donate (will be referred to as the RTFM tax)". 

You downloaded a playlist while putting the channel id as identifier...
I think i seriously made it simple, and this is the only tool of its kind for youtube content.
Do generate your own api key and put in settings or it will often not match metadata (too many users)
