### ISSUE TITLE
Provide Youtube channel artwork to collections

### ISSUE THREAD

**Issue by djmixman** [ZeroQI/YouTube-Agent.bundle#4]
It would be nice to see channel artwork imported for known channels when using collections.

If there is a [Channel ID] in the Collection grouping folder than have it import from that user.

**Comment by ZeroQI** [comment]
i cannot find any information about updating a collection metadata.
i know how to add a collection to a movie|Series

**Comment by djmixman** [comment]
Spent an hour or more last night trying to figure it out myself. I wished Plex would document their product 😞 

If I run across anything i'll let you know.

**Comment by ZeroQI** [comment]
that is why i removed support for playlist id on season folders, by using channel or playlist id on series folder, it populates more metadata. working on scanner ang guid in agent

**Comment by ZeroQI** [comment]
not possible to edit collections metadata manually, just create the collection from the agent side
