### ISSUE TITLE
youtube-dl's "--write-info-json" local json file option support

### ISSUE THREAD

**Issue by ZeroQI** [ZeroQI/YouTube-Agent.bundle#40]
It is possible to instruct YouTubeDL to generate a local Json file with: youtube-dl.exe KJB_RyESQqs --write-info-json --skip-download -o "[%(id)s].%(ext)s"

Example attached: [KJB_RyESQqs.info.json.txt](https://github.com/ZeroQI/YouTube-Agent.bundle/files/4871457/KJB_RyESQqs.info.json.txt)

The aim would be to make the agent use local metadata in the local file, if present:
- If the local file exists, load locally metadata from json file, otherwise do as usual.

**Comment by Banner-Keith** [comment]
Hi @ZeroQI I took a crack at this and I believe I have it working properly at least for TV Series libraries. I do not have a Movie library to test it on. Would you like me to create a fork and open a PR for you to review?

**Comment by ZeroQI** [comment]
@Banner-Keith Yes please.  I could expend on that to support the movie library

**Comment by Banner-Keith** [comment]
I believe the code is done for the movie library part too. Just haven't tested it yet. I'll try to get the PR up later tonight.

**Comment by Banner-Keith** [comment]
= #42

**Comment by glensc** [comment]
Documenting this: https://github.com/ZeroQI/YouTube-Agent.bundle/pull/100
