### ISSUE TITLE
videos not getting metadata

### ISSUE THREAD

**Issue by ecto1a2003** [ZeroQI/YouTube-Agent.bundle#41]
plex version : qnap v1.19.5.3112

file structure:
v:/internet/%(uploader)s/%(playlist_title)s [%(playlist_id)s]/%(playlist_index)s - %(title)s [%(id)s].%(ext)s

library root: v:/internet/

some videos show up but dont get matched some dont seem to ever shoe up or show up days later

[com.plexapp.agents.youtube.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/4973853/com.plexapp.agents.youtube.log)
[com.plexapp.system.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/4973854/com.plexapp.system.log)

**Comment by ecto1a2003** [comment]
looks like its quota related

**Comment by ZeroQI** [comment]
From the readme:

> Requirements
> - Do create your own YouTube API key and replace in ASS code and agent settings
