### ISSUE TITLE
UnboundLocalError: local variable 'series_root_folder' referenced before assignment

### ISSUE THREAD

**Issue by morlanth** [ZeroQI/YouTube-Agent.bundle#49]
I've noticed lately that some metadata is not populating. Using the latest pull of ASS and YouTube agent.

The logs show the following: https://pastebin.com/raw/GxApS1NL

**Comment by ZeroQI** [comment]
Can you check using the pull request just now?

**Comment by ZeroQI** [comment]
No answer in a month, closing

**Comment by randompasser** [comment]
Issue still presists on 44992f4. The offending variable in my setup is `channel_title`
[com.plexapp.agents.youtube.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/5816659/com.plexapp.agents.youtube.log)
