### ISSUE TITLE
Provide latest episode artwork to (non-playlist) Series folders.

### ISSUE THREAD

**Issue by djmixman** [ZeroQI/YouTube-Agent.bundle#5]
It would nice to see artwork on non-playlist based series folders. The best solution I can think of would probably be to pull the artwork from the most recent episode.

**Comment by ZeroQI** [comment]
So are artworks OK on playlist based series folder?
If so can add the functionnality

**Comment by djmixman** [comment]
I would say if there is artwork available for a playlist then use that, and if no playlist-id is available then use the most recent episode.

**Comment by ZeroQI** [comment]
metadata fields for series:
- metadata.posters
- metadata.art
- metadata.banners
- metadata.seasons[season].posters
- metadata.seasons[season].episodes[episode].thumbs

I already use the playlist image as poster but size is mismatch so it cuts the sides
i can pull the channel banner/background as metadata.art. is that what you mean 
Do you want to use a video screenshot as metadata.art ? Please give an example...

**Comment by ZeroQI** [comment]
Done on latest code
Please test and close if resolved
