### ISSUE TITLE
Request: Update documentation to include metadata source 

### ISSUE THREAD

**Issue by Jordan-Nelson** [ZeroQI/YouTube-Agent.bundle#54]
I just got this working, and so far it seems pretty great.

I ran into a bit of trouble getting it setup. When I dug into the logs I had an error:

```
IOError: [Errno 2] No such file or directory: '/<MEDIA_PATH>/<CHANNEL> [<CHANNEL_ID>]/<EPISODE> [<EPISODE_ID>].info.json'
```

It looked like it was either trying to read from or write to a file that doesn't exist. Switching the metadata source from `jsonWithApaBackup` to `ApiOnly` resolved the issue. I almost gave up when I finally found the issue in the log and happened to remember seeing that option in the settings.

Maybe I missed something in the setup, but I was trying to follow the docs as close as I possibly could. I used youtube-dl with the exact naming as in the readme. If `jsonWithApaBackup` is the default, but no json file causes an issue, maybe there should be some note to switch that?

It's possible I am just missing something. Let me know if I am.

**Comment by ZeroQI** [comment]
Didn't i fixed this 2 month ago?
https://github.com/ZeroQI/YouTube-Agent.bundle/commit/27edbb6b63bf771d9deae00f11376f3380e1c16a

**Comment by ZeroQI** [comment]
Solved in https://github.com/ZeroQI/YouTube-Agent.bundle/commit/44992f4d358c7ec41b743ab22d5d28fa63b5d9bb
