### ISSUE TITLE
Problem with video titles with  "#x#" in them

### ISSUE THREAD

**Issue by GhostGuy9** [ZeroQI/YouTube-Agent.bundle#65]
This happens to get recognized by Plex's default series code where it gets recognized as "Season # x Episode #" wanted to say I found a small fix by just adding "01x" in front of the title of each vid. 

By is there a way to remove the search for that and force it as season 1 sense YouTube channels dont entirely have seasons?

**Comment by ZeroQI** [comment]
Readme states

> Naming convention for TV Series library:
> 
> movies have to be put in identically named folder named exactly the same as the YouTube video or have youtube video id
> series foldername with with youtube playlist id '[PLxxxxxxxxxxxxxxxx]' in title or inside a youtube.id file at its root
> series foldername with with youtube channel id '[UCxxxxxxxxxxxxxxxx]' in title or inside a youtube.id file at its root

Notes
- wtf is "Plex's default series code"
- if giving channel id, season will be the year
- no impacted title example provided, so cannot ensure it uses supported naming convention
- Scanner logs not provided
- Agent logs not provided
- Numbering is a **SCANNER** issue, 1x4 is a supported numbering format for s01e04 so ASS scanner working as designed
