### ISSUE TITLE
Thumbnails being added to series poster, not episode thumbs

### ISSUE THREAD

**Issue by durmonator** [ZeroQI/YouTube-Agent.bundle#73]
Hey, I have recently just started to use this plugin and I am finding that the thumbs for the "episodes" are getting added into the show poster, as seen here:

![image](https://user-images.githubusercontent.com/40207045/110017717-6c09bb00-7d1e-11eb-923d-4c8ceba79d54.png)

I can provide logs, but as this is, in the eyes of the scanner being successful, will they be helpful? If so, just ping me and I'll get them asap for you

**Comment by ZeroQI** [comment]
Please try this major rewrite new branch, i tested and look fine in regard to your issue

**Comment by ZeroQI** [comment]
Merge to master branch, please test, it should be better

**Comment by reddragonguy** [comment]
i've tested this and the issue is still there.

**Comment by ZeroQI** [comment]
metadata.posters at fault then in episode loop part of code
there is code to add the screencap of first video to posters, but if you keep deleting videos, first video willl change and update to the posters again...

Comment lines 456 and 502 and report
`                    metadata.posters[thumb] = Proxy.Media(picture, sort_order=1)`
