### ISSUE TITLE
Channel metadata no longer added to playlist

### ISSUE THREAD

**Issue by micahmo** [ZeroQI/YouTube-Agent.bundle#77]
Hi @ZeroQI,

Back again. :-) I discovered a small issue from the rewrite. I'm not sure if it's intentional. When [this line](https://github.com/ZeroQI/YouTube-Agent.bundle/blob/f2b424620098410cc2453f80f7a10930152a0eef/Contents/Code/__init__.py#L308) changed to `elif`, it became restricted to channels. However, some of the things are very useful for playlists, too, such as...
 - Channel description (if playlist description is empty)
 - Role (cast) with channel name and picture
 - Channel banner
 
I looked through it, and I guess the only thing that shouldn't apply (if it's already a playlist) is title. The code already checks if `json_playlist_details` has certain properties, so I think it was originally planned to augment the playlist info.

I understand that it's an extra API call, so maybe you made this change intentionally?

Either way, I pushed a fix in a fork. I didn't open a PR in case you didn't want to make this change. Again, I'm not sure if you purposely eliminated this code to prevent an additional API call. (BTW, I also added an additional way to get a banner based on what I was seeing in the API respones.)

micahmo/YouTube-Agent.bundle@ab625de

Let me know what you think.

**Comment by ZeroQI** [comment]
Oversight indeed, i regrouped to reduce the number of tests, but fewer API calls are good... 
Push the PR and will add to master. Functiions should not regress...

On an unrelated note, you can look at the latest note on that bug report, i should add date-based series to ASS for channels to solve episode numbering related issues
https://github.com/ZeroQI/Absolute-Series-Scanner/issues/343
