### ISSUE TITLE
Channels don't show their true channel name

### ISSUE THREAD

**Issue by reddragonguy** [ZeroQI/YouTube-Agent.bundle#80]
Hi,  

I just have a video file `/media/youtube/Emergency_Awesome [UCDiFRMQWpcp8_KD4vwIVicw]/20210317 - Justice_League_Snyder_Cut_Trailer_-_Darkseid_Kills_The_Justice_League_and_Green_Lantern_Breakdown [qwtK4BDw1Pw].mp4` and the channel name is set to `Emergency_Awesome` instead of `Emergency Awesome`.

Shouldn't the channel name from YouTube override the channel name that was generated from the folder?

**Comment by ZeroQI** [comment]
If you create several series folder with videos from the same channel because there is no playlist available, it make no sense to label each series with the channel name

**Comment by reddragonguy** [comment]
I'm sorry, i don't think i understand your reply.  there's only one folder for one channel and one show.  When using the option of `--restrict-filenames`, yt-dl will replace spaces with dashes as my example shows above.  The TV show that's created should have the channel name instead of the folder name with the underscore, shouldn't it?

**Comment by ZeroQI** [comment]
Users have the right to have multiples series folders taken from the same channel (if there is no playlist for example):
- Wandavision [UCDiFRMQWpcp8_KD4vwIVicw]
- Justice League [UCDiFRMQWpcp8_KD4vwIVicw]
- Falcon and winter Soldier  [UCDiFRMQWpcp8_KD4vwIVicw]

**Forcing the same channel name would group all, which is not desired, furthermore some user may not want to label the series created as per the channel name.**

Why do you use "--restrict-filenames"? It does restrict filenames to only ASCII characters, and avoid "&" and spaces in filenames, but these don't cause issues to my knowledge (it does in folder name though)

**Comment by reddragonguy** [comment]
it's an all-or-none situation.  I have the issue with `™` that shows up in the folder name and to resolve it automatically, i changed the script to use `--restrict-filenames`.  It may be overkill for the one folder i'm aware of, but if i add other channels that have non-acceptable characters in their channel name or video titles, I know it'll be handled. I can't tell it which characters to keep and which characters to replace.  I use the `--batch-file FILE` to get all channels at once, so it'll end up changing all characters in all folders and filenames.

**Comment by ZeroQI** [comment]
Fair enough for --restrict filenames, would have done the same...

i could replace underscores with spaces, that is fine
I try to keep the code short and simple as it's complex enough (json, api for playlist, channel, etc..)
