### ISSUE TITLE
Not appearing for Music

### ISSUE THREAD

**Issue by RedOrion** [ZeroQI/YouTube-Agent.bundle#89]
I'm trying to use the Absolute Music Scanner with the YouTube Series agent and its not showing up. Ideally I'm trying to scan the same way as TV Shows but in the Music libraries.

**Comment by ZeroQI** [comment]
YouTube Movies and Series agent only.
Would need to rewrite the music scanner, and the agent, and label your files and folders accordingly....
It isn't planned but I would assist if you wanted to add support for it and had questions...
