### ISSUE TITLE
Certain youtube channels arent matched correctly

### ISSUE THREAD

**Issue by gguy825** [ZeroQI/YouTube-Agent.bundle#94]
I currently have 17 channels downloaded on plex but one in particular, Kurzgesagt – In a Nutshell [UCsXVk37bltHxD1rDPwtNM8Q], isn't matching no matter what i try. Is there anything I am missing to properly match channels?

**Comment by ZeroQI** [comment]
Missing the logs outlined in the readme troubleshooting section, namely the agent logs showing the search

**Comment by gguy825** [comment]
> Missing the logs outlined in the readme troubleshooting section, namely the agent logs showing the search

Ive downloaded the logs but the youtube agent log isnt included in the zip. The agent is installed since i can select the "youtubeseries" agent and it properly scrapes information for the folders but its not included in the logs.

**Comment by gguy825** [comment]
Ok its started to work properly now for some reason. I did nothing but run another scan.
